// ===========================================================================
// Glyph Code Generator — Express Routes
// Phase B: Compiler Core
//
// Ruby-inspired convention over configuration (L2).
// Service definitions generate complete Express routers with:
//   - Authentication middleware
//   - Rate limiting
//   - Pagination
//   - Input validation (via generated Zod schemas)
//   - CRUD operations
// ===========================================================================

export function generateRoutes(ast) {
  const chunks = [];
  chunks.push(`// Auto-generated by Glyph compiler v0.1.0`);
  chunks.push(`// DO NOT EDIT — deterministic output from .glyph source`);
  chunks.push(`\nimport express from 'express';`);
  chunks.push(`import { rateLimit } from 'express-rate-limit';`);

  // Import all generated schemas
  const models = ast.blocks.filter(b => b.kind === 'ModelDef');
  const schemaImports = models.map(m =>
    `${m.name}Schema, ${m.name}CreateSchema, ${m.name}UpdateSchema`
  ).join(', ');
  chunks.push(`import { ${schemaImports} } from './types.js';`);
  chunks.push(`import { db } from './db.js';`);
  chunks.push(`import { authenticate, authorize, validate } from './middleware.js';\n`);

  // Generate routes for each service
  const services = ast.blocks.filter(b => b.kind === 'ServiceDef');
  for (const service of services) {
    chunks.push(generateServiceRouter(service, ast));
    chunks.push('');
  }

  // Export all routers
  chunks.push(`// Router registry`);
  chunks.push(`export const routers = {`);
  for (const service of services) {
    const routerName = toRouterName(service.name);
    chunks.push(`  '/${toRoutePath(service.name)}': ${routerName},`);
  }
  chunks.push(`};`);

  return chunks.join('\n');
}

function toSnakeCase(name) {
  return name.replace(/([A-Z])/g, (m, p, i) => (i > 0 ? '_' : '') + m.toLowerCase());
}

function toRoutePath(name) {
  return toSnakeCase(name).replace(/_/g, '-');
}

function toRouterName(name) {
  return name.charAt(0).toLowerCase() + name.slice(1) + 'Router';
}

function toTableName(modelName) {
  return toSnakeCase(modelName) + 's';
}

function generateServiceRouter(service, ast) {
  const lines = [];
  const routerName = toRouterName(service.name);
  const basePath = toRoutePath(service.name);

  lines.push(`// Service: ${service.name}`);
  lines.push(`export const ${routerName} = express.Router();\n`);

  for (const action of service.actions) {
    if (action.kind === 'ServiceTransitionRef') {
      lines.push(generateTransitionEndpoint(action, routerName, ast));
      continue;
    }

    const { verb, model, clauses, modifiers } = action;
    const tableName = toTableName(model);
    const hasAuth = modifiers.some(m => m.type === 'auth' || m.type === 'admin');
    const isPublic = modifiers.some(m => m.type === 'public');
    const isAdmin = modifiers.some(m => m.type === 'admin');
    const rateLimit = modifiers.find(m => m.type === 'limit');
    const pageSize = modifiers.find(m => m.type === 'page');
    const roleModifier = modifiers.find(m => m.type === 'role');

    // Build middleware chain
    const middleware = [];
    if (rateLimit) {
      middleware.push(`rateLimit({ windowMs: ${getWindowMs(rateLimit.value.unit)}, max: ${rateLimit.value.amount} })`);
    }
    if (hasAuth && !isPublic) middleware.push('authenticate');
    if (isAdmin) middleware.push(`authorize('admin')`);
    if (roleModifier) middleware.push(`authorize('${roleModifier.value}')`);

    const mwStr = middleware.length > 0 ? middleware.join(', ') + ', ' : '';

    switch (verb) {
      case 'create':
        lines.push(generateCreateRoute(routerName, model, tableName, mwStr));
        break;
      case 'read': {
        const byFields = clauses.find(c => c.type === 'by');
        const byField = byFields ? byFields.fields[0] : 'id';
        lines.push(generateReadRoute(routerName, model, tableName, byField, mwStr));
        break;
      }
      case 'update': {
        const byFields = clauses.find(c => c.type === 'by');
        const byField = byFields ? byFields.fields[0] : 'id';
        lines.push(generateUpdateRoute(routerName, model, tableName, byField, mwStr));
        break;
      }
      case 'delete': {
        const byFields = clauses.find(c => c.type === 'by');
        const byField = byFields ? byFields.fields[0] : 'id';
        lines.push(generateDeleteRoute(routerName, model, tableName, byField, mwStr));
        break;
      }
      case 'list': {
        const whereFields = clauses.find(c => c.type === 'where');
        const size = pageSize ? pageSize.value : 50;
        lines.push(generateListRoute(routerName, model, tableName, whereFields?.fields || [], size, mwStr));
        break;
      }
      case 'search':
        lines.push(generateSearchRoute(routerName, model, tableName, mwStr));
        break;
    }
    lines.push('');
  }

  return lines.join('\n');
}

function getWindowMs(unit) {
  const map = {
    'second': 1000, 'seconds': 1000,
    'minute': 60000, 'minutes': 60000, 'min': 60000,
    'hour': 3600000, 'hours': 3600000,
    'day': 86400000, 'days': 86400000,
  };
  return map[unit] || 60000;
}

function generateCreateRoute(router, model, table, mw) {
  return `${router}.post('/',
  ${mw}validate(${model}CreateSchema),
  async (req, res, next) => {
    try {
      const data = req.validatedBody;
      const result = await db.query(
        \`INSERT INTO ${table} (\${Object.keys(data).join(', ')})
         VALUES (\${Object.keys(data).map((_, i) => \`$\${i + 1}\`).join(', ')})
         RETURNING *\`,
        Object.values(data)
      );
      res.status(201).json(result.rows[0]);
    } catch (err) { next(err); }
  }
);`;
}

function generateReadRoute(router, model, table, byField, mw) {
  return `${router}.get('/:${byField}',
  ${mw}async (req, res, next) => {
    try {
      const result = await db.query(
        \`SELECT * FROM ${table} WHERE ${byField} = $1\`,
        [req.params.${byField}]
      );
      if (result.rows.length === 0) return res.status(404).json({ error: '${model} not found' });
      res.json(result.rows[0]);
    } catch (err) { next(err); }
  }
);`;
}

function generateUpdateRoute(router, model, table, byField, mw) {
  return `${router}.patch('/:${byField}',
  ${mw}validate(${model}UpdateSchema),
  async (req, res, next) => {
    try {
      const data = req.validatedBody;
      const setClauses = Object.keys(data).map((k, i) => \`\${k} = $\${i + 2}\`).join(', ');
      const result = await db.query(
        \`UPDATE ${table} SET \${setClauses} WHERE ${byField} = $1 RETURNING *\`,
        [req.params.${byField}, ...Object.values(data)]
      );
      if (result.rows.length === 0) return res.status(404).json({ error: '${model} not found' });
      res.json(result.rows[0]);
    } catch (err) { next(err); }
  }
);`;
}

function generateDeleteRoute(router, model, table, byField, mw) {
  return `${router}.delete('/:${byField}',
  ${mw}async (req, res, next) => {
    try {
      const result = await db.query(
        \`DELETE FROM ${table} WHERE ${byField} = $1 RETURNING id\`,
        [req.params.${byField}]
      );
      if (result.rows.length === 0) return res.status(404).json({ error: '${model} not found' });
      res.status(204).send();
    } catch (err) { next(err); }
  }
);`;
}

function generateListRoute(router, model, table, whereFields, pageSize, mw) {
  const filterLogic = whereFields.length > 0
    ? `const filters = [];
      const values = [];
      let paramIdx = 1;
      ${whereFields.map(f => `
      if (req.query.${f}) {
        filters.push(\`${f} = $\${paramIdx++}\`);
        values.push(req.query.${f});
      }`).join('')}
      const whereClause = filters.length > 0 ? 'WHERE ' + filters.join(' AND ') : '';`
    : `const whereClause = '';
      const values = [];`;

  return `${router}.get('/',
  ${mw}async (req, res, next) => {
    try {
      const page = parseInt(req.query.page) || 1;
      const limit = ${pageSize};
      const offset = (page - 1) * limit;
      ${filterLogic}
      const countResult = await db.query(
        \`SELECT COUNT(*) FROM ${table} \${whereClause}\`,
        values
      );
      const total = parseInt(countResult.rows[0].count);
      values.push(limit, offset);
      const result = await db.query(
        \`SELECT * FROM ${table} \${whereClause} ORDER BY created_at DESC LIMIT $\${values.length - 1} OFFSET $\${values.length}\`,
        values
      );
      res.json({
        data: result.rows,
        pagination: { page, limit, total, pages: Math.ceil(total / limit) }
      });
    } catch (err) { next(err); }
  }
);`;
}

function generateSearchRoute(router, model, table, mw) {
  return `${router}.get('/search',
  ${mw}async (req, res, next) => {
    try {
      const { q, ...filters } = req.query;
      const conditions = [];
      const values = [];
      let paramIdx = 1;
      if (q) {
        conditions.push(\`to_tsvector('english', coalesce(name, '') || ' ' || coalesce(email, '')) @@ plainto_tsquery($\${paramIdx++})\`);
        values.push(q);
      }
      for (const [key, val] of Object.entries(filters)) {
        conditions.push(\`\${key} = $\${paramIdx++}\`);
        values.push(val);
      }
      const whereClause = conditions.length > 0 ? 'WHERE ' + conditions.join(' AND ') : '';
      const result = await db.query(
        \`SELECT * FROM ${table} \${whereClause} LIMIT 50\`,
        values
      );
      res.json({ data: result.rows });
    } catch (err) { next(err); }
  }
);`;
}

function generateTransitionEndpoint(ref, router, ast) {
  const tableName = toTableName(ref.model);
  const transitionFn = `transition_${toSnakeCase(ref.model)}_${ref.field}`;

  return `${router}.post('/:id/transition',
  authenticate,
  async (req, res, next) => {
    try {
      const { id } = req.params;
      const { state } = req.body;
      if (!state) return res.status(400).json({ error: 'state is required' });

      const allowed = await db.query(
        \`SELECT ${transitionFn}($1, $2) as allowed\`,
        [id, state]
      );
      if (!allowed.rows[0].allowed) {
        return res.status(422).json({ error: \`Transition to '\${state}' not allowed\` });
      }

      const result = await db.query(
        \`UPDATE ${tableName} SET ${ref.field} = $2 WHERE id = $1 RETURNING *\`,
        [id, state]
      );
      res.json(result.rows[0]);
    } catch (err) { next(err); }
  }
);`;
}
