// ===========================================================================
// Glyph Code Generator — SQL DDL
// Phase B: Compiler Core
//
// Generates PostgreSQL DDL from model definitions.
// Includes RLS policies from classification annotations.
// ===========================================================================

const SQL_TYPE_MAP = {
  'int': 'INTEGER',
  'float': 'DOUBLE PRECISION',
  'text': 'TEXT',
  'bool': 'BOOLEAN',
  'uuid': 'UUID',
  'timestamp': 'TIMESTAMPTZ',
  'date': 'DATE',
  'time': 'TIME',
  'json': 'JSONB',
  'bytes': 'BYTEA',
};

export function generateSQL(ast) {
  const chunks = [];
  chunks.push(`-- Auto-generated by Glyph compiler v0.1.0`);
  chunks.push(`-- DO NOT EDIT — deterministic output from .glyph source`);
  chunks.push(`-- L5: Same input always produces same output\n`);

  // Enable required extensions
  chunks.push(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n`);

  // Collect models for FK resolution
  const models = ast.blocks.filter(b => b.kind === 'ModelDef');
  const customTypes = new Map();
  for (const b of ast.blocks) {
    if (b.kind === 'TypeDef') customTypes.set(b.name, b);
  }

  for (const model of models) {
    chunks.push(generateCreateTable(model, customTypes));
    chunks.push('');

    // RLS policies from classification
    const rls = generateRLS(model);
    if (rls) {
      chunks.push(rls);
      chunks.push('');
    }

    // Indexes
    const indexes = generateIndexes(model);
    if (indexes) {
      chunks.push(indexes);
      chunks.push('');
    }
  }

  // Transition tables (valid_transitions from §3)
  const transitions = ast.blocks.filter(b => b.kind === 'TransitionDef');
  for (const trans of transitions) {
    chunks.push(generateTransitionDDL(trans));
    chunks.push('');
  }

  // Rules → database constraints and triggers
  const rulesDefs = ast.blocks.filter(b => b.kind === 'RulesDef');
  for (const rulesDef of rulesDefs) {
    chunks.push(generateRulesDDL(rulesDef));
    chunks.push('');
  }

  return chunks.join('\n');
}

function toSnakeCase(name) {
  return name.replace(/([A-Z])/g, (m, p, i) => (i > 0 ? '_' : '') + m.toLowerCase());
}

function generateCreateTable(model, customTypes) {
  const tableName = toSnakeCase(model.name) + 's';
  const lines = [];
  lines.push(`CREATE TABLE ${tableName} (`);

  const columnDefs = [];
  const constraints = [];

  for (const field of model.fields) {
    const colDef = generateColumn(field, model, customTypes);
    columnDefs.push(colDef);

    if (field.isKey) {
      constraints.push(`  PRIMARY KEY (${field.name})`);
    }
    if (field.isUnique) {
      constraints.push(`  UNIQUE (${field.name})`);
    }
    if (field.type.variant === 'relation') {
      const refTable = toSnakeCase(field.type.value.target) + 's';
      constraints.push(`  FOREIGN KEY (${field.name}_id) REFERENCES ${refTable}(id) ON DELETE CASCADE`);
    }
  }

  // Add audit columns
  columnDefs.push(`  updated_at TIMESTAMPTZ DEFAULT NOW()`);

  const allDefs = [...columnDefs, ...constraints];
  lines.push(allDefs.join(',\n'));
  lines.push(`);\n`);

  // Auto-update trigger for updated_at
  lines.push(`CREATE OR REPLACE FUNCTION update_${tableName}_updated_at()`);
  lines.push(`RETURNS TRIGGER AS $$`);
  lines.push(`BEGIN`);
  lines.push(`  NEW.updated_at = NOW();`);
  lines.push(`  RETURN NEW;`);
  lines.push(`END;`);
  lines.push(`$$ LANGUAGE plpgsql;\n`);
  lines.push(`CREATE TRIGGER ${tableName}_updated_at`);
  lines.push(`  BEFORE UPDATE ON ${tableName}`);
  lines.push(`  FOR EACH ROW EXECUTE FUNCTION update_${tableName}_updated_at();`);

  return lines.join('\n');
}

function generateColumn(field, model, customTypes) {
  let sqlType;
  const { type } = field;

  if (type.variant === 'base') {
    sqlType = SQL_TYPE_MAP[type.value] || 'TEXT';
  } else if (type.variant === 'ref') {
    // Custom type — resolve to base type
    const customType = customTypes.get(type.value);
    if (customType) {
      sqlType = SQL_TYPE_MAP[customType.baseType] || 'TEXT';
    } else {
      sqlType = 'TEXT';
    }
  } else if (type.variant === 'relation') {
    // FK — store as UUID
    return `  ${field.name}_id UUID NOT NULL`;
  } else if (type.variant === 'union') {
    // Enum type
    const members = type.value.filter(m => typeof m === 'string');
    const enumName = `${toSnakeCase(model.name)}_${field.name}_enum`;
    // We'll use CHECK constraint instead of CREATE TYPE for simplicity
    const values = members.map(m => `'${m}'`).join(', ');
    let col = `  ${field.name} TEXT CHECK (${field.name} IN (${values}))`;
    if (!field.isOptional) col += ' NOT NULL';
    if (field.defaultValue) col += ` DEFAULT '${field.defaultValue}'`;
    return col;
  }

  let col = `  ${field.name} ${sqlType}`;

  if (!field.isOptional && !field.isKey) col += ' NOT NULL';

  // Default values
  const def = field.defaultValue;
  if (def === 'now') col += ' DEFAULT NOW()';
  else if (def === 'auto' || def === 'uuid_generate') col += ' DEFAULT uuid_generate_v4()';
  else if (def) col += ` DEFAULT '${def}'`;

  // Range constraints
  for (const mod of field.modifiers) {
    if (mod.modifier === 'constraint' && mod.value.op === '..') {
      const [min, max] = mod.value.value;
      if (type.value === 'text') {
        col += ` CHECK (length(${field.name}) BETWEEN ${min} AND ${max})`;
      } else {
        col += ` CHECK (${field.name} BETWEEN ${min} AND ${max})`;
      }
    }
    if (mod.modifier === 'constraint' && ['>=', '<=', '>', '<'].includes(mod.value.op)) {
      col += ` CHECK (${field.name} ${mod.value.op} ${mod.value.value})`;
    }
  }

  return col;
}

function generateRLS(model) {
  if (!model.classification.level && !model.classification.ownedBy) return null;

  const tableName = toSnakeCase(model.name) + 's';
  const lines = [];

  lines.push(`-- RLS policies for ${model.name} [${model.classification.level || 'default'}]`);
  lines.push(`ALTER TABLE ${tableName} ENABLE ROW LEVEL SECURITY;\n`);

  if (model.classification.ownedBy) {
    const ownerField = model.classification.ownedBy + '_id';
    lines.push(`-- Ownership policy: rows accessible only by their owner`);
    lines.push(`CREATE POLICY ${tableName}_owner_policy ON ${tableName}`);
    lines.push(`  USING (${ownerField} = current_setting('app.current_user_id')::uuid);`);
  }

  if (model.classification.level === 'confidential' || model.classification.level === 'restricted') {
    lines.push(`\n-- Audit logging for ${model.classification.level} data`);
    lines.push(`CREATE TABLE ${tableName}_audit_log (`);
    lines.push(`  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),`);
    lines.push(`  ${toSnakeCase(model.name)}_id UUID NOT NULL REFERENCES ${tableName}(id),`);
    lines.push(`  action TEXT NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE', 'SELECT')),`);
    lines.push(`  actor_id UUID,`);
    lines.push(`  changed_fields JSONB,`);
    lines.push(`  created_at TIMESTAMPTZ DEFAULT NOW()`);
    lines.push(`);\n`);

    lines.push(`CREATE OR REPLACE FUNCTION ${tableName}_audit_trigger()`);
    lines.push(`RETURNS TRIGGER AS $$`);
    lines.push(`BEGIN`);
    lines.push(`  INSERT INTO ${tableName}_audit_log (${toSnakeCase(model.name)}_id, action, actor_id, changed_fields)`);
    lines.push(`  VALUES (`);
    lines.push(`    COALESCE(NEW.id, OLD.id),`);
    lines.push(`    TG_OP,`);
    lines.push(`    current_setting('app.current_user_id', true)::uuid,`);
    lines.push(`    CASE WHEN TG_OP = 'DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END`);
    lines.push(`  );`);
    lines.push(`  RETURN COALESCE(NEW, OLD);`);
    lines.push(`END;`);
    lines.push(`$$ LANGUAGE plpgsql;\n`);

    lines.push(`CREATE TRIGGER ${tableName}_audit`);
    lines.push(`  AFTER INSERT OR UPDATE OR DELETE ON ${tableName}`);
    lines.push(`  FOR EACH ROW EXECUTE FUNCTION ${tableName}_audit_trigger();`);
  }

  return lines.join('\n');
}

function generateIndexes(model) {
  const tableName = toSnakeCase(model.name) + 's';
  const indexes = [];

  for (const field of model.fields) {
    if (field.isIndex) {
      indexes.push(`CREATE INDEX idx_${tableName}_${field.name} ON ${tableName}(${field.name});`);
    }
    if (field.type.variant === 'relation') {
      indexes.push(`CREATE INDEX idx_${tableName}_${field.name}_id ON ${tableName}(${field.name}_id);`);
    }
  }

  return indexes.length > 0 ? indexes.join('\n') : null;
}

function generateTransitionDDL(transition) {
  const tableName = `${toSnakeCase(transition.model)}_${transition.field}_transitions`;
  const lines = [];

  lines.push(`-- Valid transitions for ${transition.model}.${transition.field}`);
  lines.push(`CREATE TABLE ${tableName} (`);
  lines.push(`  from_state TEXT NOT NULL,`);
  lines.push(`  to_state TEXT NOT NULL,`);
  lines.push(`  guard_function TEXT,`);
  lines.push(`  time_constraint INTERVAL,`);
  lines.push(`  PRIMARY KEY (from_state, to_state)`);
  lines.push(`);\n`);

  // Insert valid transitions
  for (const rule of transition.rules) {
    if (rule.actions.some(a => a.type === 'deny')) continue; // Skip deny rules

    const from = rule.from === '_' ? '*' : rule.from;
    const to = rule.to === '_' ? '*' : rule.to;
    const guards = rule.actions
      .filter(a => a.type === 'require')
      .map(a => a.value);
    const timeConstraint = rule.actions.find(a => a.type === 'within');

    const guardStr = guards.length > 0 ? `'${guards.join(',')}'` : 'NULL';
    const timeStr = timeConstraint
      ? `'${timeConstraint.value.amount} ${timeConstraint.value.unit}'::INTERVAL`
      : 'NULL';

    lines.push(`INSERT INTO ${tableName} (from_state, to_state, guard_function, time_constraint)`);
    lines.push(`  VALUES ('${from}', '${to}', ${guardStr}, ${timeStr});`);
  }

  // Transition guard function
  lines.push(`\nCREATE OR REPLACE FUNCTION transition_${toSnakeCase(transition.model)}_${transition.field}(`);
  lines.push(`  p_id UUID, p_new_state TEXT`);
  lines.push(`) RETURNS BOOLEAN AS $$`);
  lines.push(`DECLARE`);
  lines.push(`  v_current TEXT;`);
  lines.push(`  v_allowed BOOLEAN;`);
  lines.push(`BEGIN`);
  lines.push(`  SELECT ${transition.field} INTO v_current FROM ${toSnakeCase(transition.model)}s WHERE id = p_id;`);
  lines.push(`  SELECT EXISTS (`);
  lines.push(`    SELECT 1 FROM ${tableName}`);
  lines.push(`    WHERE (from_state = v_current OR from_state = '*')`);
  lines.push(`    AND (to_state = p_new_state OR to_state = '*')`);
  lines.push(`  ) INTO v_allowed;`);
  lines.push(`  RETURN v_allowed;`);
  lines.push(`END;`);
  lines.push(`$$ LANGUAGE plpgsql;`);

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Rules → Database Constraints and Triggers
// ---------------------------------------------------------------------------

function generateRulesDDL(rulesDef) {
  const lines = [];
  lines.push(`-- Business rules: ${rulesDef.name}`);

  for (const rule of rulesDef.rules) {
    switch (rule.kind) {
      case 'DenyRule':
        lines.push(generateDenyTrigger(rule, rulesDef.name));
        break;
      case 'RequireRule':
        lines.push(generateRequireTrigger(rule, rulesDef.name));
        break;
      case 'LimitRule':
        lines.push(generateLimitDDL(rule, rulesDef.name));
        break;
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateDenyTrigger(rule, rulesName) {
  const tableName = toSnakeCase(rule.model) + 's';
  const opMap = {
    'delete': 'DELETE', 'update': 'UPDATE', 'create': 'INSERT',
    'archive': 'UPDATE', 'restore': 'UPDATE',
  };
  const op = opMap[rule.verb] || 'DELETE';
  const fnName = `deny_${rule.verb}_${tableName}`;

  return `-- Rule: deny ${rule.verb} ${rule.model}
CREATE OR REPLACE FUNCTION ${fnName}()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION '${rule.verb} on ${rule.model} is denied by ${rulesName}';
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ${fnName}_trigger
  BEFORE ${op} ON ${tableName}
  FOR EACH ROW EXECUTE FUNCTION ${fnName}();`;
}

function generateRequireTrigger(rule, rulesName) {
  const tableName = toSnakeCase(rule.field.model) + 's';
  const fnName = `require_${rule.requirement}_${tableName}_${rule.field.field}`;
  const condition = `NEW.${rule.field.field} ${rule.op} ${formatSqlValue(rule.value)}`;

  return `-- Rule: ${rule.field.model}.${rule.field.field} ${rule.op} ${rule.value} requires ${rule.requirement}
CREATE OR REPLACE FUNCTION ${fnName}()
RETURNS TRIGGER AS $$
BEGIN
  IF ${condition} THEN
    IF NOT EXISTS (
      SELECT 1 FROM approvals
      WHERE entity_type = '${rule.field.model}'
        AND entity_id = NEW.id
        AND approval_type = '${rule.requirement}'
        AND status = 'approved'
    ) THEN
      RAISE EXCEPTION '${rule.field.model} with ${rule.field.field} ${rule.op} ${rule.value} requires ${rule.requirement}';
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ${fnName}_trigger
  BEFORE INSERT OR UPDATE ON ${tableName}
  FOR EACH ROW EXECUTE FUNCTION ${fnName}();`;
}

function generateLimitDDL(rule, rulesName) {
  const sourceTable = toSnakeCase(rule.field.model) + 's';
  const targetEntity = rule.entity;
  const trackingTable = `${sourceTable}_${targetEntity}_limits`;
  const fnName = `enforce_${targetEntity}_limit_${sourceTable}`;

  const periodMap = {
    'second': 'second', 'minute': 'minute', 'hour': 'hour',
    'day': 'day', 'week': 'week', 'month': 'month',
    'seconds': 'second', 'minutes': 'minute', 'hours': 'hour',
    'days': 'day', 'weeks': 'week', 'months': 'month',
  };
  const period = periodMap[rule.timeUnit] || 'month';

  return `-- Rule: ${rule.field.model}.${rule.field.field} = ${rule.value} limits ${rule.limit} ${targetEntity}/${rule.timeUnit}
CREATE TABLE IF NOT EXISTS ${trackingTable} (
  source_id UUID NOT NULL,
  period_start TIMESTAMPTZ NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (source_id, period_start)
);

CREATE OR REPLACE FUNCTION ${fnName}()
RETURNS TRIGGER AS $$
DECLARE
  v_source_value TEXT;
  v_count INTEGER;
  v_period_start TIMESTAMPTZ;
BEGIN
  SELECT ${rule.field.field} INTO v_source_value
  FROM ${sourceTable}
  WHERE id = NEW.${toSnakeCase(rule.field.model)}_id;

  IF v_source_value = ${formatSqlValue(rule.value)} THEN
    v_period_start := date_trunc('${period}', NOW());

    INSERT INTO ${trackingTable} (source_id, period_start, count)
    VALUES (NEW.${toSnakeCase(rule.field.model)}_id, v_period_start, 1)
    ON CONFLICT (source_id, period_start)
    DO UPDATE SET count = ${trackingTable}.count + 1
    RETURNING count INTO v_count;

    IF v_count > ${rule.limit} THEN
      RAISE EXCEPTION '${rule.field.model} with ${rule.field.field} = ${rule.value} is limited to ${rule.limit} ${targetEntity} per ${rule.timeUnit}';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ${fnName}_trigger
  BEFORE INSERT ON ${targetEntity}
  FOR EACH ROW EXECUTE FUNCTION ${fnName}();`;
}

function formatSqlValue(value) {
  if (typeof value === 'number' || !isNaN(Number(value))) return value;
  return `'${value}'`;
}
