// ===========================================================================
// Glyph Code Generator — Rules Middleware
// Phase C: Rules compilation to API middleware
//
// Each rule becomes an Express middleware that enforces the business
// constraint at the API layer (defense in depth — DB triggers are the
// second line of defense).
// ===========================================================================

export function generateRulesMiddleware(ast) {
  const rulesDefs = ast.blocks.filter(b => b.kind === 'RulesDef');
  if (rulesDefs.length === 0) return null;

  const chunks = [];
  chunks.push(`// Auto-generated by Glyph compiler v0.1.0`);
  chunks.push(`// Business rules middleware — defense in depth with DB triggers`);
  chunks.push(`\nimport { db } from './db.js';\n`);

  for (const rulesDef of rulesDefs) {
    chunks.push(generateRulesModule(rulesDef));
    chunks.push('');
  }

  // Export combined middleware factory
  chunks.push(generateMiddlewareRegistry(rulesDefs));

  return chunks.join('\n');
}

function toSnakeCase(name) {
  return name.replace(/([A-Z])/g, (m, p, i) => (i > 0 ? '_' : '') + m.toLowerCase());
}

function generateRulesModule(rulesDef) {
  const lines = [];
  lines.push(`// Rules: ${rulesDef.name}`);
  lines.push(`// ` + '-'.repeat(58));

  for (const rule of rulesDef.rules) {
    switch (rule.kind) {
      case 'DenyRule':
        lines.push(generateDenyMiddleware(rule, rulesDef.name));
        break;
      case 'RequireRule':
        lines.push(generateRequireMiddleware(rule, rulesDef.name));
        break;
      case 'LimitRule':
        lines.push(generateLimitMiddleware(rule, rulesDef.name));
        break;
    }
    lines.push('');
  }

  return lines.join('\n');
}

function generateDenyMiddleware(rule, rulesName) {
  // deny delete Invoice → middleware that rejects DELETE requests for that model
  const fnName = `deny${capitalize(rule.verb)}${rule.model}`;
  const httpMethod = verbToMethod(rule.verb);

  return `/**
 * Rule: deny ${rule.verb} ${rule.model}
 * Source: ${rulesName}
 * Rejects all ${rule.verb} operations on ${rule.model}.
 */
export function ${fnName}(req, res, next) {
  if (req.method === '${httpMethod}') {
    return res.status(403).json({
      error: '${rule.verb} on ${rule.model} is denied',
      rule: '${rulesName}',
      code: 'RULE_DENIED',
    });
  }
  next();
}`;
}

function generateRequireMiddleware(rule, rulesName) {
  // Invoice.amount > 10000 requires board_approval
  // → middleware that checks the condition and requires approval
  const fnName = `require${capitalize(rule.requirement)}For${rule.field.model}`;
  const tableName = toSnakeCase(rule.field.model) + 's';

  return `/**
 * Rule: ${rule.field.model}.${rule.field.field} ${rule.op} ${rule.value} requires ${rule.requirement}
 * Source: ${rulesName}
 * Checks if the operation triggers an approval requirement.
 */
export async function ${fnName}(req, res, next) {
  try {
    const fieldValue = req.body?.${rule.field.field} ?? req.validatedBody?.${rule.field.field};

    // Check if the condition is met
    if (fieldValue !== undefined && compare(fieldValue, '${rule.op}', ${formatJsValue(rule.value)})) {
      // Check if approval exists
      const entityId = req.params.id || req.body?.id;
      if (entityId) {
        const approval = await db.query(
          \`SELECT 1 FROM approvals
           WHERE entity_type = '${rule.field.model}'
             AND entity_id = $1
             AND approval_type = '${rule.requirement}'
             AND status = 'approved'\`,
          [entityId]
        );
        if (approval.rows.length === 0) {
          return res.status(422).json({
            error: '${rule.field.model} with ${rule.field.field} ${rule.op} ${rule.value} requires ${rule.requirement}',
            rule: '${rulesName}',
            code: 'APPROVAL_REQUIRED',
            approval_type: '${rule.requirement}',
          });
        }
      } else {
        // New entity — flag that approval will be needed
        req.pendingApprovals = req.pendingApprovals || [];
        req.pendingApprovals.push({
          type: '${rule.requirement}',
          reason: '${rule.field.field} ${rule.op} ${rule.value}',
        });
      }
    }

    next();
  } catch (err) { next(err); }
}`;
}

function generateLimitMiddleware(rule, rulesName) {
  // Customer.tier = free limits 5 invoices/month
  // → middleware that checks rate against the tracking table
  const fnName = `enforce${capitalize(rule.entity)}LimitFor${rule.field.model}`;
  const sourceTable = toSnakeCase(rule.field.model) + 's';
  const trackingTable = `${sourceTable}_${rule.entity}_limits`;

  const periodMap = {
    'second': 'second', 'minute': 'minute', 'hour': 'hour',
    'day': 'day', 'week': 'week', 'month': 'month',
    'seconds': 'second', 'minutes': 'minute', 'hours': 'hour',
    'days': 'day', 'weeks': 'week', 'months': 'month',
  };
  const period = periodMap[rule.timeUnit] || 'month';

  return `/**
 * Rule: ${rule.field.model}.${rule.field.field} = ${rule.value} limits ${rule.limit} ${rule.entity}/${rule.timeUnit}
 * Source: ${rulesName}
 * Enforces rate limit at the API layer before hitting the DB trigger.
 */
export async function ${fnName}(req, res, next) {
  try {
    const sourceId = req.body?.${toSnakeCase(rule.field.model)}_id || req.params.${toSnakeCase(rule.field.model)}_id;
    if (!sourceId) return next();

    // Check source entity's field value
    const source = await db.query(
      \`SELECT ${rule.field.field} FROM ${sourceTable} WHERE id = $1\`,
      [sourceId]
    );
    if (source.rows.length === 0) return next();

    if (String(source.rows[0].${rule.field.field}) === String(${formatJsValue(rule.value)})) {
      // Check current count
      const result = await db.query(
        \`SELECT COALESCE(SUM(count), 0) as total
         FROM ${trackingTable}
         WHERE source_id = $1
           AND period_start >= date_trunc('${period}', NOW())\`,
        [sourceId]
      );
      const currentCount = parseInt(result.rows[0].total);

      if (currentCount >= ${rule.limit}) {
        return res.status(429).json({
          error: '${rule.field.model} with ${rule.field.field} = ${rule.value} is limited to ${rule.limit} ${rule.entity} per ${rule.timeUnit}',
          rule: '${rulesName}',
          code: 'RATE_LIMIT_EXCEEDED',
          limit: ${rule.limit},
          current: currentCount,
          period: '${rule.timeUnit}',
        });
      }
    }

    next();
  } catch (err) { next(err); }
}`;
}

function generateMiddlewareRegistry(rulesDefs) {
  const lines = [];
  lines.push(`// Middleware registry — apply to routes by model`);
  lines.push(`// Usage: router.use(rulesMiddleware.Invoice);`);
  lines.push(`export const rulesMiddleware = {`);

  // Group rules by model
  const byModel = new Map();
  for (const rulesDef of rulesDefs) {
    for (const rule of rulesDef.rules) {
      const model = rule.model || rule.field?.model;
      if (!model) continue;
      if (!byModel.has(model)) byModel.set(model, []);
      byModel.get(model).push({ rule, rulesName: rulesDef.name });
    }
  }

  for (const [model, entries] of byModel) {
    const fns = entries.map(({ rule, rulesName }) => {
      switch (rule.kind) {
        case 'DenyRule': return `deny${capitalize(rule.verb)}${rule.model}`;
        case 'RequireRule': return `require${capitalize(rule.requirement)}For${rule.field.model}`;
        case 'LimitRule': return `enforce${capitalize(rule.entity)}LimitFor${rule.field.model}`;
      }
    }).filter(Boolean);
    lines.push(`  ${model}: [${fns.join(', ')}],`);
  }

  lines.push(`};\n`);

  // Utility: comparison helper
  lines.push(`// Comparison helper for rule evaluation`);
  lines.push(`function compare(a, op, b) {`);
  lines.push(`  const numA = Number(a), numB = Number(b);`);
  lines.push(`  const useNum = !isNaN(numA) && !isNaN(numB);`);
  lines.push(`  const va = useNum ? numA : a, vb = useNum ? numB : b;`);
  lines.push(`  switch (op) {`);
  lines.push(`    case '=': return va == vb;`);
  lines.push(`    case '!=': return va != vb;`);
  lines.push(`    case '>': return va > vb;`);
  lines.push(`    case '<': return va < vb;`);
  lines.push(`    case '>=': return va >= vb;`);
  lines.push(`    case '<=': return va <= vb;`);
  lines.push(`    default: return false;`);
  lines.push(`  }`);
  lines.push(`}`);

  return lines.join('\n');
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function verbToMethod(verb) {
  const map = {
    'create': 'POST', 'read': 'GET', 'update': 'PATCH',
    'delete': 'DELETE', 'list': 'GET', 'search': 'GET',
  };
  return map[verb] || 'DELETE';
}

function formatJsValue(value) {
  if (typeof value === 'number' || !isNaN(Number(value))) return value;
  return `'${value}'`;
}
