// ===========================================================================
// Glyph Code Generator — Pipeline Handlers
// Phase C: Pipeline compilation with error handling and retry semantics
//
// Each pipeline becomes an async handler function with:
//   - Trigger registration (event listener / cron / DB trigger)
//   - Step-by-step execution with context passing
//   - Error handling with retry, escalation, and rollback
// ===========================================================================

export function generatePipelines(ast) {
  const pipelines = ast.blocks.filter(b => b.kind === 'PipelineDef');
  if (pipelines.length === 0) return null;

  const chunks = [];
  chunks.push(`// Auto-generated by Glyph compiler v0.1.0`);
  chunks.push(`// Pipeline handlers — event-driven step chains with error handling`);
  chunks.push(`\nimport { db } from './db.js';`);
  chunks.push(`import { EventEmitter } from 'events';`);
  chunks.push(`\nexport const pipelineEvents = new EventEmitter();\n`);

  // Step function stubs
  const allSteps = new Set();
  for (const p of pipelines) {
    for (const step of p.steps) allSteps.add(step);
  }
  chunks.push(generateStepStubs(allSteps));
  chunks.push('');

  // Pipeline handlers
  for (const pipeline of pipelines) {
    chunks.push(generatePipelineHandler(pipeline));
    chunks.push('');
  }

  // Registration
  chunks.push(generatePipelineRegistration(pipelines));

  return chunks.join('\n');
}

function toSnakeCase(name) {
  return name.replace(/([A-Z])/g, (m, p, i) => (i > 0 ? '_' : '') + m.toLowerCase());
}

function generateStepStubs(steps) {
  const lines = [];
  lines.push(`// Pipeline step implementations`);
  lines.push(`// Each step receives a context object and returns an updated context.`);
  lines.push(`// Replace these stubs with real implementations.\n`);

  lines.push(`const steps = {`);
  for (const step of steps) {
    lines.push(`  ${step}: async (ctx) => {`);
    lines.push(`    console.log('[pipeline] step: ${step}', { entityId: ctx.entityId });`);
    lines.push(`    // TODO: implement ${step}`);
    lines.push(`    return ctx;`);
    lines.push(`  },`);
  }
  lines.push(`};\n`);

  lines.push(`/** Register a real step implementation. */`);
  lines.push(`export function registerStep(name, fn) {`);
  lines.push(`  steps[name] = fn;`);
  lines.push(`}`);

  return lines.join('\n');
}

function generatePipelineHandler(pipeline) {
  const lines = [];
  const fnName = `handle${pipeline.name}`;
  const { errorHandler } = pipeline;

  lines.push(`/**`);
  lines.push(` * Pipeline: ${pipeline.name}`);
  lines.push(` * Trigger: ${describeTrigger(pipeline.trigger)}`);
  lines.push(` * Steps: ${pipeline.steps.join(' → ')}`);
  if (errorHandler) {
    lines.push(` * On failure: ${describeErrorHandler(errorHandler)}`);
  }
  lines.push(` */`);
  lines.push(`export async function ${fnName}(event) {`);
  lines.push(`  const ctx = {`);
  lines.push(`    pipeline: '${pipeline.name}',`);
  lines.push(`    entityId: event.entityId || event.id,`);
  lines.push(`    entity: event.entity || event,`);
  lines.push(`    startedAt: new Date(),`);
  lines.push(`    completedSteps: [],`);
  lines.push(`    errors: [],`);
  lines.push(`  };\n`);

  lines.push(`  const pipelineSteps = [${pipeline.steps.map(s => `'${s}'`).join(', ')}];`);
  lines.push(`  let lastCompletedIndex = -1;\n`);

  // Retry wrapper
  if (errorHandler && errorHandler.type === 'retry') {
    lines.push(`  const MAX_RETRIES = ${errorHandler.retries};`);
    lines.push(`  let attempt = 0;\n`);
    lines.push(`  while (attempt <= MAX_RETRIES) {`);
    lines.push(`    try {`);
    lines.push(`      for (let i = lastCompletedIndex + 1; i < pipelineSteps.length; i++) {`);
    lines.push(`        const stepName = pipelineSteps[i];`);
    lines.push(`        const stepFn = steps[stepName];`);
    lines.push(`        if (!stepFn) throw new Error(\`Pipeline step '\${stepName}' not implemented\`);`);
    lines.push(`        await stepFn(ctx);`);
    lines.push(`        ctx.completedSteps.push(stepName);`);
    lines.push(`        lastCompletedIndex = i;`);
    lines.push(`      }`);
    lines.push(`      // All steps completed successfully`);
    lines.push(`      pipelineEvents.emit('${toSnakeCase(pipeline.name)}:complete', ctx);`);
    lines.push(`      return ctx;`);
    lines.push(`    } catch (err) {`);
    lines.push(`      attempt++;`);
    lines.push(`      ctx.errors.push({ attempt, step: pipelineSteps[lastCompletedIndex + 1], error: err.message, at: new Date() });`);
    lines.push(`      console.error(\`[pipeline] ${pipeline.name} attempt \${attempt} failed at step '\${pipelineSteps[lastCompletedIndex + 1]}': \${err.message}\`);`);
    lines.push(``);
    lines.push(`      if (attempt > MAX_RETRIES) {`);

    // Fallback action
    if (errorHandler.fallback === 'escalate') {
      lines.push(`        // Escalate to higher tier`);
      lines.push(`        pipelineEvents.emit('${toSnakeCase(pipeline.name)}:escalate', {`);
      lines.push(`          ...ctx,`);
      lines.push(`          failedAt: pipelineSteps[lastCompletedIndex + 1],`);
      lines.push(`          totalAttempts: attempt,`);
      lines.push(`        });`);
      lines.push(`        console.error('[pipeline] ${pipeline.name}: max retries exceeded, escalating');`);
    } else if (errorHandler.fallback === 'rollback') {
      lines.push(`        // Rollback completed steps in reverse`);
      lines.push(`        for (let i = ctx.completedSteps.length - 1; i >= 0; i--) {`);
      lines.push(`          const rollbackFn = steps[\`rollback_\${ctx.completedSteps[i]}\`];`);
      lines.push(`          if (rollbackFn) {`);
      lines.push(`            try { await rollbackFn(ctx); } catch (rbErr) {`);
      lines.push(`              console.error(\`[pipeline] ${pipeline.name}: rollback of \${ctx.completedSteps[i]} failed: \${rbErr.message}\`);`);
      lines.push(`            }`);
      lines.push(`          }`);
      lines.push(`        }`);
      lines.push(`        pipelineEvents.emit('${toSnakeCase(pipeline.name)}:rolled_back', ctx);`);
    } else if (errorHandler.fallback === 'skip') {
      lines.push(`        // Skip failed step and continue`);
      lines.push(`        console.warn('[pipeline] ${pipeline.name}: skipping failed step');`);
      lines.push(`        lastCompletedIndex++;`);
      lines.push(`        attempt = 0; // reset retries for next step`);
      lines.push(`        continue;`);
    } else {
      // 'fail' or default
      lines.push(`        pipelineEvents.emit('${toSnakeCase(pipeline.name)}:failed', ctx);`);
      lines.push(`        console.error('[pipeline] ${pipeline.name}: max retries exceeded, failing');`);
    }

    lines.push(`        return ctx;`);
    lines.push(`      }`);
    lines.push(``);
    lines.push(`      // Wait before retry (exponential backoff)`);
    lines.push(`      await new Promise(r => setTimeout(r, Math.min(1000 * Math.pow(2, attempt - 1), 30000)));`);
    lines.push(`    }`);
    lines.push(`  }`);
  } else {
    // No retry — simple sequential execution
    lines.push(`  try {`);
    lines.push(`    for (const stepName of pipelineSteps) {`);
    lines.push(`      const stepFn = steps[stepName];`);
    lines.push(`      if (!stepFn) throw new Error(\`Pipeline step '\${stepName}' not implemented\`);`);
    lines.push(`      await stepFn(ctx);`);
    lines.push(`      ctx.completedSteps.push(stepName);`);
    lines.push(`    }`);
    lines.push(`    pipelineEvents.emit('${toSnakeCase(pipeline.name)}:complete', ctx);`);
    lines.push(`  } catch (err) {`);
    lines.push(`    ctx.errors.push({ step: pipelineSteps[ctx.completedSteps.length], error: err.message, at: new Date() });`);

    if (errorHandler && errorHandler.type === 'rollback') {
      lines.push(`    // Rollback completed steps in reverse`);
      lines.push(`    for (let i = ctx.completedSteps.length - 1; i >= 0; i--) {`);
      lines.push(`      const rollbackFn = steps[\`rollback_\${ctx.completedSteps[i]}\`];`);
      lines.push(`      if (rollbackFn) {`);
      lines.push(`        try { await rollbackFn(ctx); } catch (rbErr) {`);
      lines.push(`          console.error(\`[pipeline] ${pipeline.name}: rollback of \${ctx.completedSteps[i]} failed: \${rbErr.message}\`);`);
      lines.push(`        }`);
      lines.push(`      }`);
      lines.push(`    }`);
      lines.push(`    pipelineEvents.emit('${toSnakeCase(pipeline.name)}:rolled_back', ctx);`);
    } else {
      lines.push(`    pipelineEvents.emit('${toSnakeCase(pipeline.name)}:failed', ctx);`);
    }

    lines.push(`  }`);
  }

  lines.push(`  return ctx;`);
  lines.push(`}`);

  return lines.join('\n');
}

function generatePipelineRegistration(pipelines) {
  const lines = [];
  lines.push(`// Pipeline registration`);
  lines.push(`// Call registerPipelines() after setting up your event system.\n`);
  lines.push(`export function registerPipelines(eventBus) {`);

  for (const pipeline of pipelines) {
    const fnName = `handle${pipeline.name}`;
    const { trigger } = pipeline;

    switch (trigger.type) {
      case 'transition':
        lines.push(`  // ${pipeline.name}: triggered when ${trigger.config.model}.${trigger.config.field} → ${trigger.config.state}`);
        lines.push(`  eventBus.on('${toSnakeCase(trigger.config.model)}.${trigger.config.field}.${trigger.config.state}', ${fnName});`);
        break;
      case 'action':
        lines.push(`  // ${pipeline.name}: triggered on ${trigger.config.verb} ${trigger.config.model}`);
        lines.push(`  eventBus.on('${trigger.config.verb}.${toSnakeCase(trigger.config.model)}', ${fnName});`);
        break;
      case 'event':
        lines.push(`  // ${pipeline.name}: triggered on ${trigger.config.event}`);
        lines.push(`  eventBus.on('${trigger.config.event}', ${fnName});`);
        break;
      case 'schedule':
        lines.push(`  // ${pipeline.name}: runs every ${trigger.config.amount} ${trigger.config.unit}`);
        lines.push(`  // Note: schedule registration requires a cron library — wire externally`);
        lines.push(`  // cron.schedule('${durationToCron(trigger.config)}', ${fnName});`);
        break;
    }
  }

  lines.push(`}\n`);

  // Pipeline metadata for the orchestration layer
  lines.push(`/** Pipeline metadata for agent system / §8 pathway views */`);
  lines.push(`export const pipelineManifest = ${JSON.stringify(
    pipelines.map(p => ({
      name: p.name,
      trigger: p.trigger.type,
      steps: p.steps,
      errorStrategy: p.errorHandler ? {
        type: p.errorHandler.type,
        retries: p.errorHandler.retries,
        fallback: p.errorHandler.fallback,
      } : null,
    })), null, 2)};`);

  return lines.join('\n');
}

function describeTrigger(trigger) {
  switch (trigger.type) {
    case 'transition': return `${trigger.config.model}.${trigger.config.field} → ${trigger.config.state}`;
    case 'action': return `on ${trigger.config.verb} ${trigger.config.model}`;
    case 'event': return `on event ${trigger.config.event}`;
    case 'schedule': return `every ${trigger.config.amount} ${trigger.config.unit}`;
  }
}

function describeErrorHandler(eh) {
  if (eh.type === 'retry') {
    return `retry ${eh.retries}${eh.fallback ? ` then ${eh.fallback}` : ''}`;
  }
  return eh.type;
}

function durationToCron(duration) {
  // Best-effort cron expression
  switch (duration.unit) {
    case 'minute': case 'minutes': return `*/${duration.amount} * * * *`;
    case 'hour': case 'hours': return `0 */${duration.amount} * * *`;
    case 'day': case 'days': return `0 0 */${duration.amount} * *`;
    default: return `0 0 * * *`;
  }
}
