// ===========================================================================
// Glyph Code Generator — TypeScript + Zod
// Phase B: Compiler Core
//
// L4: Types as simultaneous spec, validation, schema, and docs.
// A single model definition generates TypeScript types AND Zod validators.
// ===========================================================================

const BASE_TYPE_MAP = {
  'int': { ts: 'number', zod: 'z.number().int()' },
  'float': { ts: 'number', zod: 'z.number()' },
  'text': { ts: 'string', zod: 'z.string()' },
  'bool': { ts: 'boolean', zod: 'z.boolean()' },
  'uuid': { ts: 'string', zod: 'z.string().uuid()' },
  'timestamp': { ts: 'Date', zod: 'z.coerce.date()' },
  'date': { ts: 'string', zod: 'z.string().date()' },
  'time': { ts: 'string', zod: 'z.string().time()' },
  'json': { ts: 'unknown', zod: 'z.unknown()' },
  'bytes': { ts: 'Buffer', zod: 'z.instanceof(Buffer)' },
};

export function generateTypes(ast) {
  const chunks = [];
  chunks.push(`// Auto-generated by Glyph compiler v0.1.0`);
  chunks.push(`// DO NOT EDIT — deterministic output from .glyph source`);
  chunks.push(`// L5: Same input always produces same output`);
  chunks.push(`\nimport { z } from 'zod';\n`);

  // Collect custom type defs for reference
  const customTypes = new Map();

  for (const block of ast.blocks) {
    if (block.kind === 'TypeDef') {
      const { code, zodCode } = generateTypeDef(block);
      customTypes.set(block.name, block);
      chunks.push(code);
      chunks.push(zodCode);
      chunks.push('');
    }
    if (block.kind === 'ModelDef') {
      chunks.push(generateModelTypes(block, customTypes));
      chunks.push('');
    }
  }

  return chunks.join('\n');
}

function generateTypeDef(typeDef) {
  const { name, baseType, constraints } = typeDef;
  const base = BASE_TYPE_MAP[baseType];

  if (!base) {
    // Reference to another custom type
    return {
      code: `export type ${name} = ${baseType};`,
      zodCode: `export const ${name}Schema = ${baseType}Schema;`,
    };
  }

  let zodChain = base.zod;
  for (const c of constraints) {
    zodChain = applyConstraintToZod(zodChain, c, baseType);
  }

  return {
    code: `export type ${name} = ${base.ts};`,
    zodCode: `export const ${name}Schema = ${zodChain};`,
  };
}

function applyConstraintToZod(zodChain, constraint, baseType) {
  switch (constraint.op) {
    case '>=': return `${zodChain}.min(${constraint.value})`;
    case '<=': return `${zodChain}.max(${constraint.value})`;
    case '>': return `${zodChain}.refine(v => v > ${constraint.value}, { message: 'Must be > ${constraint.value}' })`;
    case '<': return `${zodChain}.refine(v => v < ${constraint.value}, { message: 'Must be < ${constraint.value}' })`;
    case '~':
      const patterns = {
        'email': '.email()',
        'url': '.url()',
        'ip': '.ip()',
        'uuid': '.uuid()',
      };
      return `${zodChain}${patterns[constraint.value] || `.regex(/${constraint.value}/)`}`;
    case '..':
      if (baseType === 'text') {
        return `${zodChain}.min(${constraint.value[0]}).max(${constraint.value[1]})`;
      }
      return `${zodChain}.min(${constraint.value[0]}).max(${constraint.value[1]})`;
    default:
      return zodChain;
  }
}

function generateModelTypes(model, customTypes) {
  const { name, classification, fields } = model;
  const lines = [];

  // JSDoc with classification metadata
  lines.push(`/**`);
  lines.push(` * @model ${name}`);
  if (classification.level) lines.push(` * @classification ${classification.level}`);
  if (classification.ownedBy) lines.push(` * @ownedBy ${classification.ownedBy}`);
  lines.push(` */`);

  // TypeScript interface
  lines.push(`export interface ${name} {`);
  for (const field of fields) {
    const tsType = fieldToTypeScript(field, customTypes);
    const optional = field.isOptional ? '?' : '';
    lines.push(`  ${field.name}${optional}: ${tsType};`);
  }
  lines.push(`}\n`);

  // Zod schema
  lines.push(`export const ${name}Schema = z.object({`);
  for (const field of fields) {
    const zodType = fieldToZod(field, customTypes);
    lines.push(`  ${field.name}: ${zodType},`);
  }
  lines.push(`});\n`);

  // Create schema (without auto-generated fields)
  const createFields = fields.filter(f => !f.isKey && f.defaultValue === null && f.name !== 'created');
  lines.push(`export const ${name}CreateSchema = z.object({`);
  for (const field of createFields) {
    const zodType = fieldToZod(field, customTypes);
    lines.push(`  ${field.name}: ${zodType},`);
  }
  lines.push(`});\n`);

  // Update schema (all fields optional)
  const updateFields = fields.filter(f => !f.isKey && f.name !== 'created');
  lines.push(`export const ${name}UpdateSchema = z.object({`);
  for (const field of updateFields) {
    const zodType = fieldToZod(field, customTypes);
    lines.push(`  ${field.name}: ${zodType}.optional(),`);
  }
  lines.push(`});`);

  // Type aliases for create/update
  lines.push(`\nexport type ${name}Create = z.infer<typeof ${name}CreateSchema>;`);
  lines.push(`export type ${name}Update = z.infer<typeof ${name}UpdateSchema>;`);

  return lines.join('\n');
}

function fieldToTypeScript(field, customTypes) {
  const { type } = field;

  if (type.variant === 'base') {
    const mapped = BASE_TYPE_MAP[type.value];
    return mapped ? mapped.ts : type.value;
  }

  if (type.variant === 'ref') {
    // Custom type reference
    return type.value;
  }

  if (type.variant === 'relation') {
    return `string`; // Foreign keys are stored as IDs
  }

  if (type.variant === 'union') {
    const members = type.value.map(m => typeof m === 'string' ? `'${m}'` : m);
    return members.join(' | ');
  }

  return 'unknown';
}

function fieldToZod(field, customTypes) {
  const { type } = field;
  let zod;

  if (type.variant === 'base') {
    const mapped = BASE_TYPE_MAP[type.value];
    zod = mapped ? mapped.zod : `z.unknown()`;
  } else if (type.variant === 'ref') {
    zod = `${type.value}Schema`;
  } else if (type.variant === 'relation') {
    zod = `z.string().uuid()`; // FK as UUID
  } else if (type.variant === 'union') {
    const members = type.value.map(m => typeof m === 'string' ? m : m);
    zod = `z.enum([${members.map(m => `'${m}'`).join(', ')}])`;
  } else {
    zod = 'z.unknown()';
  }

  // Apply constraints from modifiers
  for (const mod of field.modifiers) {
    if (mod.modifier === 'constraint') {
      zod = applyConstraintToZod(zod, mod.value, type.value);
    }
  }

  // Default value
  const def = field.defaultValue;
  if (def && def !== 'now' && def !== 'auto') {
    zod = `${zod}.default('${def}')`;
  }

  if (field.isOptional) {
    zod = `${zod}.optional().nullable()`;
  }

  return zod;
}
